### ISSUE TITLE
wine不能运行

### ISSUE THREAD

**Issue by ghhcbef** [ceeyourbac/czfscion#1]
ERROR Code - 100 Unknown                                                                            
Possible cause: █████████████████████████████████████████████████████████████                       
Possible solution: ████████████████████████████████████████████████████████████████████             
If it can't be solved: please go to GitHub of czfscion to feed back your problem. We may solve the e
rror of czfscion calculator in the next version                                                     
Our GitHub issue address：https://github.com/ceeyourbac/czfscion/issues

**Comment by ceeyourbac** [comment]
We don't accept any feedback on Android or Linux 爬

**Comment by ghhcbef** [comment]
你敢close我把你骨灰扬了呜呜

**Comment by ceeyourbac** [comment]
We will soon launch a czfscion calculator for Linux to support the Ubuntu and Debian(.deb) platform!

**Comment by ceeyourbac** [comment]
soon

**Comment by ghhcbef** [comment]
不是debian系的怎么办 上架aur火速奥

**Comment by ceeyourbac** [comment]
> 不是aur系的怎么办 上架debian火速奥

aur又不能跑deb

**Comment by ghhcbef** [comment]
edited by ____

**Comment by ceeyourbac** [comment]
CzfsCion Software will update today @ghhcbef

**Comment by ceeyourbac** [comment]
****
